Practica Calificada/lab04/lab04/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('registro/', include('registro.urls')),
    path('admin/', admin.site.urls),
]

Practica Calificada/lab04/registro/urls.py
from unicodedata import name
from django.urls import path

from . import views

app_name = 'registro'

urlpatterns = [
    # ex: /registro/
    path('', views.index, name='index'),
    # ex: /registro/5/
    path('<int:region_id>/', views.detalle, name='detalle'),
    # ex: /registro/candidato/5/
    path('candidato/<int:candidato_id>/', views.candidato, name='candidato'),
]

Practica Calificada/lab04/registro/models.py
from contextlib import nullcontext
from django.db import models

# Create your models here.

class Region(models.Model):
    nombre_region = models.CharField(max_length=200)
    descripcion = models.CharField(max_length=250)
    pub_date = models.DateTimeField('date published')

class Candidato(models.Model):
    region = models.ForeignKey(Region, on_delete=models.CASCADE)
    nombre_cand = models.CharField(max_length=250)
    apellido_cand = models.CharField(max_length=250)
    edad = models.IntegerField(default=22)
    ocupacion = models.CharField(max_length=200)

Practica Calificada/lab04/registro/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_list_or_404, get_object_or_404, render
from django.urls import reverse

# from django.shortcuts import render

from .models import Candidato, Region

def index(request):
    latest_question_list = Region.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'registro/index.html', context)


def detalle(request, region_id):
    region = get_object_or_404(Region, pk=region_id)
    return render(request, 'registro/detalle.html',{'region': region})

def candidato(request, candidato_id):
    candidato = get_object_or_404(Candidato, pk=candidato_id)
    return render(request, 'registro/candidato.html',{'candidato': candidato})

Practica Calificada/lab04/registro/templates/registro/candidato.html
<h1>Candidato - {{ candidato.nombre_cand }}</h1>

<ul>
    <li>Nombre: {{ candidato.nombre_cand }}</li>
    <li>Apellido: {{ candidato.apellido_cand }}</li>
    <li>Edad: {{ candidato.edad }}</li>
    <li>Ocupacion: {{ candidato.ocupacion }}</li>
</ul>

<a href="{% url 'registro:index' %}">Volver</a>

Practica Calificada/lab04/registro/templates/registro/detalle.html
<h1>{{ region.nombre_region }}</h1>

<ul>
{% for candidato in region.candidato_set.all %}
    <li>
        <a href="/registro/candidato/{{ candidato.id }}/">{{ candidato.nombre_cand }}</a>
    </li>
    
{% endfor %}
</ul>

<a href="{% url 'registro:index' %}">Volver</a>

Practica Calificada/lab04/registro/templates/registro/index.html
<h1>Regiones</h1>
{% if latest_question_list %}
    <ul>
    {% for region in latest_question_list %}
        <li>
            <a href="/registro/{{ region.id }}/">{{ region.nombre_region }}</a>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No hay Registros</p>
{% endif %}